source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PlainPing_Example', :exclusive => true do
  pod 'PlainPing', :path => '../'
end

target 'PlainPing_Tests', :exclusive => true do
  pod 'PlainPing', :path => '../'

  
end
